### ISSUE TITLE
Consider using prettier to format

### ISSUE THREAD

**Issue by rangeoshun** [orzechowskid/css-in-js.el#1]
Hi,

Nice job! I copied your solution turning parsing when idle on. I saw you've put in great effort into indentation. Have you considered adding prettier to do formatting for you?

It works great, it's customizable, and maybe you can turn it on for the css submode only.

Cheers

**Comment by orzechowskid** [comment]
thanks for the kind words!

actual indentation is just a call to `smie-indent-line`, which uses the [SMIE](https://www.gnu.org/software/emacs/manual/html_node/elisp/SMIE.html) rules pre-defined by `css-mode` to determine how much whitespace to insert.  the annoying part was how to preserve leading whitespace in the code being indented (since the Javascript string literal containing the CSS, which starts and ends outside of the css-mode subregion, could itself be indented.  the CSS needs to be indented relative to that, not to beginning-of-line).

I'm not super familiar with prettier but it looks like it operates on entire files at once, and it can insert (and remove) newlines in the code you pass it?  sending the entire buffer to prettier means replacing everything with prettier's output (which I think is a bad experience) or having to figure out where in that output our CSS lives (since it could have moved around due to newline insertion or removal).  and it looks like [prettier will strip leading whitespace from CSS-like text](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdGAmBLAzgBwBsBDATyVQCNCIwBrAbgB0oMMJ9ixsZzUBGBiAA0IDjGzRcyUMQBOciAHcACvITSUxQkrLTRlOVzpwYAZU7coAc2Qw5AVzii4AW0pxMmTwBliNh2JrOAAxCDlXYhgJG2QQYgcYCBEQAAsYV0IAdVSeOAIuODMNHmwANx5SOLBcfRBsKFw4ORgVI2tI5AAzbSbRACtcAA8AISN6UzNiVzgfBrhu3ucQQaGzButCOABFBwh4RcI+kE45Jrk4ymIPQhT8OQaYLOxMGFTkAA4ABlF7iCaskZ8HF7vlmmUFqIAI57eBtDiaeK4AC0UDgnk8KTkcBh2GxbSCnSQPSOyyarmwdkcZI2W12+wWxKWohg12er3eSAATCyjNhCBsAMIQVxEkD5ACsKQcTQAKtdNCTjmUnABJKDeWBmMAPfAwACCGrMvC2hyaAF9zUA), meaning we can't just pass it the contents of the css-mode subregion without going through the same acrobatics we already do.

do you happen to know if prettier can be configured to preserve leading whitespace in that last case?

**Comment by rangeoshun** [comment]
Actually, it respects the leading spaces for me. Just try inserting some css-in-js code into prettier on the link you've sent. 
What I want to say is that maybe formatting should not be the responsibility of this package, but you may recommend solutions like prettier, and allow for disabling indentation for cases like our company, where we all use prettier with a common config file present in each repo.

Here's how it looks for me BTW. I have prettier configured to run on save only.

![mmm-prettier](https://user-images.githubusercontent.com/1267842/97331581-d777e380-1879-11eb-8d81-648371601ca7.gif)

**Comment by orzechowskid** [comment]
right - leading spaces in your example are preserved because they're contained in a javascript string, and prettier knows how to handle js strings containing css.  the problem is that I don't have just that js string; I have a sub-region of a buffer.  that sub-region does not have the same boundaries as the js string (though they might not be hard to calculate, now that I think about it), and prettier won't do the right thing if I give it just the contents of the sub-region.

I like your idea of an option to disable formatting completely, and it won't be too hard to add.  until then, one possible workaround is to use a mode hook for scss-mode or css-mode to set [`indent-line-function`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Mode_002dSpecific-Indent.html) to something else. mmm-mode should run mode hooks when a sub-region is created, and I think `indent-line-function` is one of the values it swaps in and out as point moves from region to region.

**Comment by rangeoshun** [comment]
I'm not sure if this is a good idea or not, but you might not need to calculate offsets. You used `:front-offset 1`, so your region only needs to be wrapped into something prettier can handle like. Adding a first and last line as below.

```js
css`

display: block;
  opacity: 1;
`
```
Would result in this.
```js
css`
  display: block;
  opacity: 1;
`;
```

So you just need to drop the first and the last line and you have a region formatted correctly. Prettier does a lot more then indentation tho, so this is an opinionated suggestion, I know. People might just don't want it.

**Comment by orzechowskid** [comment]
right, that was my thought too - infer the string location from the region location.  let me think about that a bit.  meanwhile, I've added a boolean option to control what happens with indentation (see #2).

**Comment by rangeoshun** [comment]
Cool thanks!
